server:
  port: 8502
spring:
  application:
    name: "store-service"
  config:
    import: "optional:configserver:http://localhost:8401/"
  datasource:
    url: "jdbc:mysql://localhost:3306/active_kart"
    username: root
    password: Test12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
