server:
  port: 8502

spring:
  application:
    name: "store-service"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8401/"
  datasource:
    url: "jdbc:mysql://localhost:3306/active_kart"
    username: root
    password: Test12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true