services:
  network-deploy-service:
    networks:
      - active-kart-nw

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8401/
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/active_kart"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test12345