services:
  network-deploy-service:
    networks:
      - active-kart-nw

  microservice-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-eureka:
    extends:
      service: microservice-config
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8401/

  microservice-application:
    extends:
      service: microservice-eureka
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8402/eureka/
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/active_kart"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test12345
