services:
  config-service:
    image: "kart/config-service:R02"
    container_name: config-service-ms
    ports:
      - "8401:8401"
    healthcheck:
      test: "curl --fail --silent localhost:8401/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-config

  eureka-server:
    image: "kart/eureka-server:R02"
    container_name: eureka-server-ms
    ports:
      - "8402:8402"
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
    healthcheck:
      test: "curl --fail --silent localhost:8402/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka

  inventory-service:
    image: "kart/inventory-service:R02"
    container_name: inventory-service-ms
    ports:
      - "8501:8501"
    environment:
      SPRING_APPLICATION_NAME: "inventory-service"
    extends:
      file: common-config.yml
      service: microservice-application

  store-service:
    image: "kart/store-service:R02"
    container_name: store-service-ms
    ports:
      - "8502:8502"
    environment:
      SPRING_APPLICATION_NAME: "store-service"
    extends:
      file: common-config.yml
      service: microservice-application

  store-service_extra:
    image: "kart/store-service:R02"
    container_name: store-service-ms-extra
    ports:
      - "8503:8502"
    environment:
      SPRING_APPLICATION_NAME: "store-service"
    extends:
      file: common-config.yml
      service: microservice-application

networks:
  active-kart-nw:
    driver: "bridge"