services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    ports:
      - "8016:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service
  config-service:
    image: "kart/config-service:R05"
    container_name: config-service-ms
    ports:
      - "8011:8011"
    extends:
      file: common-config.yml
      service: microservice-config-base
    healthcheck:
      test: "curl --fail --silent localhost:8011/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  eureka-server:
    image: "kart/eureka-server:R05"
    container_name: eureka-server-ms
    ports:
      - "8012:8012"
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
    extends:
      file: common-config.yml
      service: microservice-eureka-base
    healthcheck:
      test: "curl --fail --silent localhost:8012/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


  inventory-service:
    image: "kart/inventory-service:R05"
    container_name: inventory-service-ms
    environment:
      SPRING_APPLICATION_NAME: "inventory-service"
    extends:
      file: common-config.yml
      service: microservice-application-base
    healthcheck:
      test: "curl --fail --silent localhost:8024/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


  store-service:
    image: "kart/store-service:R05"
    container_name: store-service-ms
    environment:
      SPRING_APPLICATION_NAME: "store-service"
    extends:
      file: common-config.yml
      service: microservice-application-base
    healthcheck:
      test: "curl --fail --silent localhost:8021/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  gateway-server:
    image: "kart/gateway-server:R05"
    container_name: gateway-server-ms
    ports:
      - "8010:8010"
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-gateway-base
    healthcheck:
      test: "curl --fail --silent localhost:8010/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  active-kart-nw:
    driver: "bridge"