services:
  config-service:
    image: "kart/config-service:R02"
    container_name: config-service-ms
    ports:
      - "8401:8401"
    healthcheck:
      test: "curl --fail --silent localhost:8401/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  inventory-service:
    image: "kart/inventory-service:R02"
    container_name: inventory-service-ms
    ports:
      - "8501:8501"
    environment:
      SPRING_APPLICATION_NAME: "inventory-service"
    depends_on:
      config-service:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  store-service:
    image: "kart/store-service:R02"
    container_name: store-service-ms
    ports:
      - "8502:8502"
    environment:
      SPRING_APPLICATION_NAME: "store-service"
    depends_on:
      config-service:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  active-kart-nw:
    driver: "bridge"